### ISSUE TITLE
Failed to load the hyperclick-octolinker package

### ISSUE THREAD

**Issue by stefanbuck** [danielbayley/atom-hyperclick-octolinker#1]
[Enter steps to reproduce:]

1. Install extension

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [hyperclick-octolinker](https://github.com/danielbayley/atom-hyperclick-octolinker) package 0.1.1

### Stack Trace

Failed to load the hyperclick-octolinker package

```
At Unexpected token function

SyntaxError: Unexpected token function
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/hyperclick-octolinker/index.coffee:3:11)
    at /packages/hyperclick-octolinker/index.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:565:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:321:22)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:473:25)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:812:34
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.4 
auto-update-packages 1.0.1 
busy-signal 1.4.3 
change-case 0.6.5 
csscomb 0.3.1 
editorconfig 2.2.2 
es6-javascript 1.0.0 
highlight-selected 0.13.1 
hyperclick 0.1.3 
hyperclick-octolinker 0.1.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.3 
sort-lines 0.14.0 
```

**Comment by danielbayley** [comment]
Hmm, so this works in the Atom Beta (which I normally use), but fails in stable! Will have to investigate further…

**Comment by danielbayley** [comment]
@stefanbuck The issue seems to be that the [do-request module is using `async`/`await`](https://github.com/OctoLinker/live-resolver/blob/master/src/utils/do-request.js#L22), which Atom stable doesn’t support yet, but apparently works in Atom Beta which is why I didn’t pick it up, along with the fact that I didn’t think to check the imported code… it wouldn’t have happened if it was compiled/published as an `npm` package. 😉

**Comment by danielbayley** [comment]
@stefanbuck I just released a workaround.
